Guest/urls.py
from django.urls import path,include

from Guest import views
app_name="webguest"
urlpatterns = [
   path('Coach/',views.Coach,name="Coach"),
   path('Shop/',views.Shop,name="Shop"),
   path('User/',views.User,name="User"),
   path('ajaxdistrict/',views.Ajaxdistrict,name="Ajaxdistrict"),
   path('ajaxplace/',views.Ajaxplace,name="Ajaxplace"),
   path('Login/',views.Login,name="Login"),
   path('',views.Index,name="Index"),
   path('Contact/',views.Contact,name="Contact"),
   path('About/',views.About,name="About"),
   
]

Shop/urls.py
from django.urls import path,include

from Shop import views
app_name="webshop"
urlpatterns = [
     path('ShopHP/',views.ShopHP,name="ShopHP"),
     path('Ajaxscategory/',views.Ajaxscategory,name="Ajaxscategory"),
     path('Product/',views.Product,name="Product"),
     path('deleteProduct<int:pid>',views.deleteProduct,name="deleteProduct"),
     path('add_photo/<int:id>',views.add_photo,name="add_photo"),
     path('ViewShop/',views.ViewShop,name="ViewShop"),# type: ignore
     path('EPShop/',views.EPShop,name="EPShop"),
     path('EditShop/',views.EditShop,name="EditShop"),
     path('Booking/',views.Bookings,name="Bookings"),# type: ignore
     path('BookingProducts/<int:id>',views.BookingProducts,name="BookingProducts"),
     path('Packed/<int:id>',views.Packed,name="Packed"),
     path('Shipped/<int:id>',views.Shipped,name="Shipped"),
     path('Delivered/<int:id>',views.Delivered,name="Delivered"),
     path('Contact/',views.Contact,name="Contact"),
     path('About/',views.About,name="About"),
     path('Logout/',views.Logout,name="Logout"),
     path('MyProducts/',views.MyProducts,name="MyProducts"),

  
]

mainpro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('wadmin/',include('wadmin.urls')),
    path('Admin/',include('Admin.urls')),
    path('',include('Guest.urls')),
    path('Coach/',include('Coach.urls')),
    path('Shop/',include('Shop.urls')),
    path('User/',include('User.urls')),
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Guest/models.py
from email.policy import default
from pyexpat import model
from Admin.models import *



# Create your models here.
class tbl_coach(models.Model):
     coach_name=models.CharField(max_length=20)
     coach_email=models.CharField(max_length=20)
     coach_contact=models.CharField(max_length=20)
     coach_gender=models.CharField(max_length=20)
     coach_dob=models.CharField(max_length=20)
     place=models.ForeignKey(tbl_place,on_delete=models.CASCADE)
     event=models.ForeignKey(tbl_event,on_delete=models.CASCADE,null=True)
     coach_address=models.CharField(max_length=50,null=True)
     coach_photo=models.FileField(upload_to='CoachDoc/')
     coach_licence=models.FileField(upload_to='Coachlic')
     coach_password=models.CharField(max_length=20)
     coach_vstatus=models.CharField(max_length=1,default="0",null=True)  




class tbl_shop(models.Model):
     shop_name=models.CharField(max_length=20)
     shop_email=models.CharField(max_length=20)
     shop_contact=models.CharField(max_length=20)
     shop_address=models.CharField(max_length=100)
     shop_photo=models.FileField(upload_to='Shopphoto/')
     shop_proof=models.FileField(upload_to='Shopproof/')
     place=models.ForeignKey(tbl_place,on_delete=models.CASCADE)
     shop_password=models.CharField(max_length=20)
     shop_vstatus=models.CharField(max_length=1,default="0")

class tbl_user(models.Model):
     user_name=models.CharField(max_length=20)
     user_email=models.CharField(max_length=20)
     user_contact=models.CharField(max_length=20)
     place=models.ForeignKey(tbl_place,on_delete=models.CASCADE)
     user_gender=models.CharField(max_length=20)
     user_address=models.CharField(max_length=500)
     user_dob=models.CharField(max_length=20)
     user_photo=models.FileField(upload_to='Userphoto/')
     user_proof=models.FileField(upload_to='Userproof/')
     user_password=models.CharField(max_length=20)
     user_vstatus=models.CharField(max_length=20,default="0",null=True)

class tbl_chat(models.Model):
    chat_content = models.CharField(max_length=500)
    chat_time = models.DateTimeField()
    chat_file = models.FileField(upload_to='ChatFiles/')
    user_from = models.ForeignKey(tbl_user,on_delete=models.CASCADE,related_name="user_from",null=True)
    user_to = models.ForeignKey(tbl_user,on_delete=models.CASCADE,related_name="user_to",null=True)
    coach_from = models.ForeignKey(tbl_coach,on_delete=models.CASCADE,related_name="coach_from",null=True)
    coach_to = models.ForeignKey(tbl_coach,on_delete=models.CASCADE,related_name="coach_to",null=True)

class tbl_queries(models.Model):
     queries_name=models.CharField(max_length=20)
     queries_email=models.CharField(max_length=20)
     queries_message=models.CharField(max_length=500)
     



class complaint(models.Model):
     complaint_title=models.CharField(max_length=500)
     user=models.ForeignKey(tbl_user,on_delete=models.CASCADE)
     coach=models.ForeignKey(tbl_coach,on_delete=models.CASCADE)
     shop=models.ForeignKey(tbl_shop,on_delete=models.CASCADE)
     complaint_content=models.CharField(max_length=500)
     comaplaint_replay=models.CharField(max_length=500)
     comaplaint_status=models.CharField(max_length=1)
     complaint_date=models.DateField()

Guest/views.py
from ctypes.wintypes import POINT
import re
from django.shortcuts import render,redirect
from Admin.models import *
from Guest.models import tbl_coach, tbl_queries, tbl_shop, tbl_user

# Create your views here.

def Coach(request):
    state=tbl_state.objects.all()
    district=tbl_district.objects.all()
    event=tbl_event.objects.all()
    if request.method == "POST":
        eventdata=tbl_event.objects.get(id=request.POST.get("txt_event"))
        place = tbl_place.objects.get(id=request.POST.get("txt_place"),)
        tbl_coach.objects.create(coach_name=request.POST.get("txt_name"),
                                 coach_email=request.POST.get("txt_email"),
                                 coach_contact=request.POST.get("txt_contact"),
                                 coach_address=request.POST.get("txt_address"),
                                 coach_gender=request.POST.get("txt_gender"),
                                 coach_dob=request.POST.get("txt_dob"),
                                 place=place,
                                 event=eventdata,
                                 coach_photo=request.FILES.get("txt_photo"),
                                 coach_licence=request.FILES.get("txt_licence"),
                                 coach_password=request.POST.get("txt_password")
                                )   
        return render(request,"Guest/coachregistration.html",{"disdata":district,"sdata":state,"edata":event})
    else:
        return render(request,"Guest/coachregistration.html",{"disdata":district,"sdata":state,"edata":event})
def Ajaxdistrict(request):
    sdata=tbl_state.objects.get(id=request.GET.get("stateid"))
    disdata=tbl_district.objects.filter(state=sdata)
    return render(request,"Guest/AjaxDistrict.html",{"district":disdata})
def Ajaxplace(request):
    disdata=tbl_district.objects.get(id=request.GET.get("distid"))
    placedata=tbl_place.objects.filter(district=disdata)
    return render(request,"Guest/AjaxPlace.html",{"Place":placedata})


def Shop(request):
    state=tbl_state.objects.all()
    district=tbl_district.objects.all()
    if request.method == "POST":
        place = tbl_place.objects.get(id=request.POST.get("txt_place"),)
        tbl_shop.objects.create(shop_name=request.POST.get("txt_name"),
                                 shop_email=request.POST.get("txt_email"),
                                 shop_contact=request.POST.get("txt_contact"),
                                 shop_address=request.POST.get("txt_address"),
                                 place=place,
                                 shop_photo=request.FILES.get("txt_photo"),
                                 shop_proof=request.FILES.get("txt_proof"),
                                 shop_password=request.POST.get("txt_password"),
                                )   
        return render(request,"Guest/shopregistration.html",{"disdata":district,"sdata":state})
    else:
        return render(request,"Guest/shopregistration.html",{"disdata":district,"sdata":state})




def User(request):
    state=tbl_state.objects.all()
    district=tbl_district.objects.all()
    if request.method == "POST":
        place = tbl_place.objects.get(id=request.POST.get("txt_place"),)
        tbl_user.objects.create( user_name=request.POST.get("txt_name"),
                                 user_email=request.POST.get("txt_email"),
                                 user_contact=request.POST.get("txt_contact"),
                                 place=place,
                                 user_gender=request.POST.get("txt_gender"),
                                 user_address=request.POST.get("txt_address"),
                                 user_dob=request.POST.get("txt_dob"),
                                 user_photo=request.FILES.get("txt_photo"),
                                 user_proof=request.FILES.get("txt_proof"),
                                 user_password=request.POST.get("txt_password"),
                                )   
        return render(request,"Guest/userregistration.html",{"disdata":district,"sdata":state})
    else:
        return render(request,"Guest/userregistration.html",{"disdata":district,"sdata":state})


def Login(request):
    if request.method=="POST":
        Email=request.POST.get("txt_email")
        Password=request.POST.get("txt_password")
        coachcount=tbl_coach.objects.filter(coach_email=Email,coach_password=Password).count()
        admincount=tbl_admin.objects.filter(admin_email=Email,admin_password=Password).count()
        shopcount=tbl_shop.objects.filter(shop_email=Email,shop_password=Password).count()
        usercount=tbl_user.objects.filter(user_email=Email,user_password=Password).count()

        if coachcount>0:
            coach = tbl_coach.objects.get(coach_email=Email,coach_password=Password)
            if coach.coach_vstatus=='0':
                return render(request,"Guest/login.html",{'msg':"Rgistration Pending"})
            elif coach.coach_vstatus=='2':
                return render(request,"Guest/login.html",{'msg':"Admin Rejected"})
            else:
                request.session["cid"] = coach.id
                return redirect("webcoach:CoachHP")
        elif usercount>0:
            user=tbl_user.objects.get(user_email=Email,user_password=Password)
            if user.user_vstatus=='0':
                return render(request,"Guest/login.html",{'msg':"Registration Pending"})
            elif user.user_vstatus=='2':
                return render(request,"Guest/login.html",{'msg':"Admin Rejeccted"})
            else:
                request.session["uid"]=user.id
                return redirect("webuser:UserHP")
        elif shopcount>0:
            shop=tbl_shop.objects.get(shop_email=Email,shop_password=Password)
            if shop.shop_vstatus=='0':
                return render(request,"Guest/login.html",{'msg':"Registration Pending"})
            elif shop.shop_vstatus=='2':
                return render(request,'Guest/login.html',{'msg':"Admin Rejected"})
            else:
                request.session["sid"]=shop.id
                return redirect("webshop:ShopHP")
        elif admincount>0:
            admin=tbl_admin.objects.get(admin_email=Email,admin_password=Password)
            request.session["aid"] = admin.id
            return redirect("xadmin:AdminHP")
            
        else:
            return render(request,"Guest/login.html",{'msg':'Incorrect Credentials'})
    else:
        return render(request,"Guest/login.html")
    

def Index(request):
    return render(request,'Guest/index.html')


def Contact(request):
    if request.method=="POST":
        tbl_queries.objects.create( queries_name=request.POST.get("txt_name"),
                                    queries_email=request.POST.get("txt_email"),
                                    queries_message=request.POST.get("txt_message"),
                                 )
        return render(request,'Guest/contact.html')
    else:
        return render(request,"Guest/contact.html")

def About(request):
    return render(request,"Guest/about.html")

Guest/templates/guest/AjaxDistrict.html
<option value="">Select</option>
{% for i in district %}
<option value="{{i.id}}">{{i.district_name}}</option>
{% endfor %}

Guest/templates/guest/AjaxPlace.html
<option value="">Select</option>
{% for i in Place %}
<option value="{{i.id}}">{{i.place_name}}</option>
{% endfor %}

Guest/templates/guest/coachregistration.html
{% extends 'Guest/header.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration Form</title>
</head>
<body>
    <form  method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
        <h2>Coach Registration</h2>
        <tr>
            <td>
        <label for="name"> Name:</label></td>
        <td><input type="text" id="txt_name" name="txt_name" required title="Name Allows Only Alphabets,Spaces and First Letter Must Be Capital Letter" pattern="^[A-Z]+[a-zA-Z ]*$"/></td>
 </tr>
 <tr>
    <td>
        <label for="email">Email:</label></td>
    <td>

    
        <input type="email" id="txt_email" name="txt_email" required>
    </td>
    </tr>
    <tr>
        <td>
            <label for="contact">Contact:</label>
        </td>
        <td>
            <input type="tel" id="txt_contact" name="txt_contact" required  pattern="[7-9]{1}[0-9]{9}" 
            title="Phone number with 7-9 and remaing 9 digit with 0-9"/>
        </td>
    </tr>
    <tr>
        <td>
            <label for="address">Address:</label>
        </td>
        <td>
            <textarea id="txt_address" name="txt_address" required>

            </textarea>
            
        </td>
    </tr>
        <tr>
            <td>
                <label for="gender">Gender:</label>
            </td>
            <td>
                <input type="radio" name="txt_gender" id="txt_gender" value="Male" required>Male
                <input type="radio" name="txt_gender" id="txt_gender" value="Female">Female
            </td>
        </tr>
        <tr>
            <td>
                <label for="dob">Date of Birth:</label>
            </td>
            <td>
                <input type="date" id="txt_dob" name="txt_dob" required>
            </td>
        </tr>
       <tr>
        <td>
            State
        </td>
        <td>
            <select name="txt_state" id="selstate" required>
                <option value="">SELECT</option>
                {% for i in sdata %}
                <option value="{{i.id}}">{{i.state_name}}</option>
                {% endfor %}
            </select>
        </td>
       </tr>
       <tr>
        <td>District</td>
        <td>
            <select name="txt_district" id="seldistrict" required>
                <option value="">SELECT</option>
            </select>
        </td>
       </tr>
       <tr>
        <td>Place</td>
        <td>
            <select name="txt_place" id="selplace" required>
                <option value="">SELECT</option>
                {% for i in plc %}
                <option value="{{i.id}}">{{i.place_name}}</option>
               {% endfor %}
            </select>
        </td>
       </tr>
       <tr>
        <td>
            Event
        </td>
        <td>
            <select name="txt_event" id="txt_event" required>
                <option value="">SELECT</option>
                {% for i in edata %}
                <option value="{{i.id}}">{{i.event_name}}</option>
               {% endfor %}
            </select>
        </td>
       </tr>
        <tr>
            <td>
                <label for="photo">Photo:</label>
            </td>
            <td>
                <input type="file" id="txt_photo" name="txt_photo" required>
            </td>
        </tr>
<tr>
    <td>
        <label for="licence">License:</label>
    </td>
    <td>
        <input type="file" id="txt_licence" name="txt_licence" required>
    </td>
</tr>
    <tr>
        <td>
            <label for="password">Password:</label>
        </td>
        <td>
            <input type="password" id="txt_password" name="txt_password" required pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters"/>
        </td>
    </tr>   
    <tr>
        <td>
            <label for="confirmpassword">Password:</label>
        </td>
        <td>
            <input type="password" id="txt_cpassword" name="txt_cpassword" required >
        </td>
    </tr>
       <tr>
        <td colspan="2" align="center">
            <button type="submit">Register</button>
        <button type="reset"> cancel</button>
        </td>
       </tr> 
    </table>
    </form>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
     $("#selstate").change(function () {
        var sid = $(this).val();
        var ur = "{% url 'webguest:Ajaxdistrict' %}";
        $.ajax({
            url: ur,
            data: { stateid: sid, },
            success: function (data) {
                $("#seldistrict").html(data);
            },
        });
    });
    $("#seldistrict").change(function () {
        var did = $(this).val();
        var ur = "{% url 'webguest:Ajaxplace' %}";
        $.ajax({
            url: ur,
            data: { distid: did, },
            success: function (data) {
                $("#selplace").html(data);
            },
        });
    });
</script>
</html>



{% endblock content %}

Guest/templates/guest/header.html
{%  load static  %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <title>ATHLETEFORGE INDEX</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Playball&display=swap" rel="stylesheet">

        <!-- Icon Font Stylesheet -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

        <!-- Libraries Stylesheet -->
        <link href="{%  static  'Main/lib/animate/animate.min.css'  %}" rel="stylesheet">
        <link href="{%  static  'Main/lib/lightbox/css/lightbox.min.css'  %}" rel="stylesheet">
        <link href="{%  static  'Main/lib/owlcarousel/owl.carousel.min.css'  %}" rel="stylesheet">

        <!-- Customized Bootstrap Stylesheet -->
        <link href="{%  static  'Main/css/bootstrap.min.css'  %}" rel="stylesheet">

        <!-- Template Stylesheet -->
        <link href="{%  static  'Main/css/style.css'  %}" rel="stylesheet">
    </head>

    <body>

        <!-- Spinner Start -->
        <div id="spinner" class="show w-100 vh-100 bg-white position-fixed translate-middle top-50 start-50  d-flex align-items-center justify-content-center">
            <div class="spinner-grow text-primary" role="status"></div>
        </div>
        <!-- Spinner End -->


        <!-- Navbar start -->
        <div class="container-fluid nav-bar">
            <div class="container">
                <nav class="navbar navbar-light navbar-expand-lg py-4">
                    <a href="{% url 'webguest:Index'%}" class="navbar-brand">
                        <h1 class="text-primary fw-bold mb-0">Athlete<span class="text-dark">FORGE</span> </h1>
                    </a>
                    <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                        <span class="fa fa-bars text-primary"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <div class="navbar-nav mx-auto" >
                            <a href="{% url 'webguest:Index'%}" class="nav-item nav-link active">Home</a>
                            <a href="{% url 'webguest:About' %}" class="nav-item nav-link">About</a>
                            <!-- <a href="service.html" class="nav-item nav-link">Trainings</a>
                            <a href="event.html" class="nav-item nav-link">Products</a>
                            <a href="service.html" class="nav-item nav-link">Coaches</a> -->
                            <!-- <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                                <div class="dropdown-menu bg-light">
                                    <a href="book.html" class="dropdown-item">Booking</a>
                                    <a href="blog.html" class="dropdown-item">Our Blog</a>
                                    <a href="team.html" class="dropdown-item">Our Team</a>
                                    <a href="testimonial.html" class="dropdown-item">Testimonial</a>
                                    <a href="404.html" class="dropdown-item">404 Page</a>
                                </div>
                            </div> -->
                            <a href="{% url 'webguest:Contact' %}" class="nav-item nav-link">Contact</a>
                        </div>
                        
                        <a href="{% url 'webguest:Login'%}" class="btn btn-primary py-3 px-5 d-none d-xl-inline-block rounded-pill">LOGIN NOW</a>
                    </div>
                </nav>
            </div>
        </div>
        <!-- Navbar End -->


        {% block content %}

        {% endblock content %}

        <!-- Footer Start -->
        <div class="container-fluid footer py-6 my-6 mb-0 bg-light wow bounceInUp" data-wow-delay="0.1s">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-item">
                            <h1 class="text-primary">Athlete<span class="text-dark">Forge</span></h1>
                            <p class="lh-lg mb-4">There cursus massa at urnaaculis estieSed aliquamellus vitae ultrs condmentum leo massamollis its estiegittis miristum.</p>
                            
                        </div>
                    </div>
                   
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-item">
                            <h4 class="mb-4">Contact Us</h4>
                            <div class="d-flex flex-column align-items-start">
                                <p><i class="fa fa-map-marker-alt text-primary me-2"></i>Kerala India</p>
                                <p><i class="fa fa-phone-alt text-primary me-2"></i> (+91) 8606469091</p>
                                <p><i class="fas fa-envelope text-primary me-2"></i> edwin321edu@gmail.com</p>
                                <p><i class="fa fa-clock text-primary me-2"></i> 26/7 Hours Service</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-item">
                            <h4 class="mb-4">Social Support</h4>
                            <div class="d-flex flex-column align-items-start">
                                <div class="footer-icon d-flex">
                                  <a class="btn btn-primary btn-sm-square me-2 rounded-circle" href=""><i class="fab fa-facebook-f"></i></a>
                                    <a class="btn btn-primary btn-sm-square me-2 rounded-circle" href=""><i class="fab fa-twitter"></i></a>
                                    <a href="#" class="btn btn-primary btn-sm-square me-2 rounded-circle"><i class="fab fa-instagram"></i></a>
                                    <a href="#" class="btn btn-primary btn-sm-square rounded-circle"><i class="fab fa-linkedin-in"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="footer-item">
                            <h4 class="mb-4">Social Gallery</h4>
                            <div class="row g-2">
                                <div class="col-4">
                                     <img src="{%  static  'Main/img/menu-01.jpg'  %}" class="img-fluid rounded-circle border border-primary p-2" alt="">
                                </div>
                                <div class="col-4">
                                     <img src="{%  static  'Main/img/menu-02.jpg'  %}" class="img-fluid rounded-circle border border-primary p-2" alt="">
                                </div>
                                <div class="col-4">
                                     <img src="{%  static  'Main/img/menu-03.jpg'  %}" class="img-fluid rounded-circle border border-primary p-2" alt="">
                                </div>
                                <div class="col-4">
                                     <img src="{%  static  'Main/img/menu-04.jpg'  %}" class="img-fluid rounded-circle border border-primary p-2" alt="">
                                </div>
                                <div class="col-4">
                                     <img src="{%  static  'Main/img/menu-05.jpg'  %}" class="img-fluid rounded-circle border border-primary p-2" alt="">
                                </div>
                                <div class="col-4">
                                     <img src="{%  static  'Main/img/menu-06.jpg'  %}" class="img-fluid rounded-circle border border-primary p-2" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Copyright Start -->
        <!-- <div class="container-fluid copyright bg-dark py-4">
            <div class="container">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        <span class="text-light"><a href="#"><i class="fas fa-copyright text-light me-2"></i>Your Site Name</a>, All right reserved.</span>
                    </div>
                    <div class="col-md-6 my-auto text-center text-md-end text-white"> -->
                        <!--/*** This template is free as long as you keep the below author’s credit link/attribution link/backlink. ***/-->
                        <!--/*** If you'd like to use the template without the below author’s credit link/attribution link/backlink, ***/-->
                        <!--/*** you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". ***/-->
                        <!-- Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a> Distributed By <a class="border-bottom" href="https://themewagon.com">ThemeWagon</a>
                    </div>
                </div>
            </div>
        </div> -->
        <!-- Copyright End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-md-square btn-primary rounded-circle back-to-top"><i class="fa fa-arrow-up"></i></a>   

        
        <!-- JavaScript Libraries -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{%  static  'Main/lib/wow/wow.min.js'  %}"></script>
        <script src="{%  static  'Main/lib/easing/easing.min.js'  %}"></script>
        <script src="{%  static  'Main/lib/waypoints/waypoints.min.js'  %}"></script>
        <script src="{%  static  'Main/lib/counterup/counterup.min.js'  %}"></script>
        <script src="{%  static  'Main/lib/lightbox/js/lightbox.min.js'  %}"></script>
        <script src="{%  static  'Main/lib/owlcarousel/owl.carousel.min.js'  %}"></script>

        <!-- Template Javascript -->
        <script src="{%  static  'Main/js/main.js'  %}"></script>
    </body>
</html>