Coach/urls.py
from django.urls import path
from Coach import views

app_name="webcoach"

urlpatterns = [
 path('CoachHP/',views.CoachHP,name="CoachHP"),
 path('ViewCoach/',views.ViewCoach,name="ViewCoach"), # type: ignore
 path('EditCoach/',views.EditCoach,name="EditCoach"),
 path('EPCoach/',views.EPCoach,name="EPCoach"), # type: ignore
 path('Trainingdetails/',views.Trainingdetails,name="Trainingdetails"),
 path('DailyPlan/<int:id>',views.DailyPlan,name="DailyPlan"),
 path('AddSubscription/',views.AddSubscription,name="AddSubscription"),
 path('Workout/<int:id>',views.Workout,name="Workout"),
 path('Followers/',views.Followers,name="Followers"),

path('chatpage/<int:id>',views.chatpage,name="chatpage"),
path('ajaxchat/',views.ajaxchat,name="ajaxchat"),
path('ajaxchatview/',views.ajaxchatview,name="ajaxchatview"),
path('clearchat/',views.clearchat,name="clearchat"),
]

Shop/urls.py
from django.urls import path,include

from Shop import views
app_name="webshop"
urlpatterns = [
     path('ShopHP/',views.ShopHP,name="ShopHP"),
     path('Ajaxscategory/',views.Ajaxscategory,name="Ajaxscategory"),
     path('Product/',views.Product,name="Product"),
     path('deleteProduct<int:pid>',views.deleteProduct,name="deleteProduct"),
     path('add_photo/<int:id>',views.add_photo,name="add_photo"),
     path('ViewShop/',views.ViewShop,name="ViewShop"),# type: ignore
     path('EPShop/',views.EPShop,name="EPShop"),
     path('EditShop/',views.EditShop,name="EditShop"),
     path('Booking/',views.Bookings,name="Bookings"),# type: ignore
     path('BookingProducts/<int:id>',views.BookingProducts,name="BookingProducts"),
     path('Packed/<int:id>',views.Packed,name="Packed"),
     path('Shipped/<int:id>',views.Shipped,name="Shipped"),
     path('Delivered/<int:id>',views.Delivered,name="Delivered"),
     path('Contact/',views.Contact,name="Contact"),
     path('About/',views.About,name="About"),
     path('Logout/',views.Logout,name="Logout"),
     path('MyProducts/',views.MyProducts,name="MyProducts"),

  
]

mainpro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('wadmin/',include('wadmin.urls')),
    path('Admin/',include('Admin.urls')),
    path('',include('Guest.urls')),
    path('Coach/',include('Coach.urls')),
    path('Shop/',include('Shop.urls')),
    path('User/',include('User.urls')),
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Coach/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from Admin.models import tbl_event
from Guest.models import tbl_coach
# Create your models here.


class tbl_trainig(models.Model):
    event=models.ForeignKey(tbl_event,on_delete=models.CASCADE)
    coach=models.ForeignKey(tbl_coach,on_delete=models.CASCADE)
    training_duration=models.CharField(max_length=20)
    training_details=models.CharField(max_length=500)

class tbl_subscription(models.Model):
    subscription_amount=models.CharField(max_length=20)
    subscription_details=models.CharField(max_length=500)
    coach = models.ForeignKey(tbl_coach,on_delete=models.SET_NULL,null=True)
    

class tbl_dailyplan(models.Model):
    training=models.ForeignKey(tbl_trainig,on_delete=models.CASCADE)
    dailyplan_day=models.CharField(max_length=20)
    dailyplan_wcount=models.CharField(max_length=20)


class tbl_workout(models.Model):
    dailyplan=models.ForeignKey(tbl_dailyplan,on_delete=models.CASCADE)
    workout_name=models.CharField(max_length=20)
    workout_discription=models.CharField(max_length=500)
    workout_file=models.FileField(upload_to='workout-file/')

Coach/views.py
from urllib import request
from django.shortcuts import render,redirect

from Guest.models import *
from Coach.models import *
from User.models import *
from .models import *
from django.db.models import Q
from datetime import datetime

# Create your views here.
def CoachHP(request):
    coach = tbl_coach.objects.get(id=request.session["cid"])
    if request.method=="POST":
        return render(request,"Coach/CoachHP.html")
    else:
        return render(request,"Coach/CoachHP.html",{"data":coach})

def ViewCoach(request):
    coach = tbl_coach.objects.get(id=request.session["cid"])
    if request.method=="POST":
        return render(request,"Coach/Viewprofile.html"),
    else:
        return render(request,"Coach/Viewprofile.html",{"data": coach})
    
def EditCoach(request):
    coach=tbl_coach.objects.get(id=request.session["cid"])
    if request.method=="POST":
        coach.coach_name=request.POST.get("txt_name")
        coach.coach_contact=request.POST.get("txt_contact")
        coach.coach_address=request.POST.get("txt_address")
        coach.save()
        return redirect("webcoach:ViewCoach")
    else:
        return render(request,"Coach/EditProfile.html",{"data":coach})
    

def EPCoach(request):
    if request.method=="POST":
        coach=tbl_coach.objects.get(id=request.session['cid'])
        opassword=request.POST.get("txt_opassword")
        npassword=request.POST.get("txt_npassword")
        cpassword=request.POST.get("txt_cpassword")
        if coach.coach_password==opassword:
            if npassword == cpassword:
                coach.coach_password=request.POST.get("txt_npassword")
                coach.save()
                return redirect("webcoach:ViewCoach")
            else:
                msg="password missmatch !"
                return render(request,"Coach/Changepassword.html",{'msg':msg})
        else:
            msg="password missmatch !"
            return render(request,"Coach/Changepassword.html",{'msg':msg})
    else:
        return render(request,"Coach/Changepassword.html")



def Trainingdetails(request):
    event=tbl_event.objects.all()
    training=tbl_trainig.objects.all()
    if request.method == "POST":
        coach = tbl_coach.objects.get(id=request.session['cid'])
        eventdata = tbl_event.objects.get(id=request.POST.get("txt_event"),)
        tbl_trainig.objects.create(coach=coach,
                                 event = eventdata,
                                 training_duration=request.POST.get("txt_duration"),
                                 training_details=request.POST.get("txt_details"),
                                 
                                )   
        return render(request,"Coach/Trainingdetails.html",{"data":event,"tdata":training})
    else:
        return render(request,"Coach/Trainingdetails.html",{"data":event,"tdata":training})  
    

    

def AddSubscription(request):
    subscription=tbl_subscription.objects.all()
    if request.method=="POST":
        tbl_subscription.objects.create(subscription_amount=request.POST.get("txt_amount"),
                                     subscription_details=request.POST.get("txt_details"),
                                     )
        return render(request,"Coach/Addsubscription.html",{"data":subscription})
    else:
        return render(request,"Coach/Addsubscription.html",{"data":subscription})
    

def DailyPlan(request,id):
    dailyplan=tbl_dailyplan.objects.all()

    if request.method=="POST":
        training = tbl_trainig.objects.get(id=id)
        tbl_dailyplan.objects.create(training=training,
                                     dailyplan_day=request.POST.get("txt_day"),
                                     dailyplan_wcount=request.POST.get("txt_workout"),
                                     )
        return render(request,"Coach/DailyPlan.html",{"data":dailyplan})
    else:
        return render(request,"Coach/DailyPlan.html",{"data":dailyplan})
    



def Workout(request,id):
    workout=tbl_workout.objects.all()
    workoutcount=tbl_workout.objects.filter(dailyplan=id).count()
    dite = tbl_dailyplan.objects.get(id=id)
    ditecount = dite.dailyplan_wcount
    if workoutcount >= int(ditecount):
        return render(request,"Coach/Workout.html",{"data":workout,"alt":1})
    else:
        if request.method=="POST":
            dailyplan=tbl_dailyplan.objects.get(id=id)
            tbl_workout.objects.create(dailyplan=dailyplan,
                                    workout_name=request.POST.get("txt_name"),
                                    workout_discription=request.POST.get("txt_discription"),
                                    workout_file=request.FILES.get("txt_file"),
                                    )
            return render(request,"Coach/Workout.html",{"msg":"Data Added..","ID":id})
        else:
            return render(request,"Coach/Workout.html",{"data":workout})
        


def Followers(request):
    follower = tbl_follow.objects.filter(coach=request.session["cid"])
    return render(request,"Coach/Followers.html",{"data":follower})

def chatpage(request,id):
    foll = tbl_follow.objects.get(id=id)
    user  = tbl_user.objects.get(id=foll.user_id)
    print(user.user_name)
    return render(request,"Coach/Chat.html",{"user":user})

def ajaxchat(request):
    from_user = tbl_coach.objects.get(id=request.session["cid"])
    to_user = tbl_user.objects.get(id=request.POST.get("tid"))
    tbl_chat.objects.create(chat_content=request.POST.get("msg"),chat_time=datetime.now(),coach_from=from_user,user_to=to_user,chat_file=request.FILES.get("file"))
    return render(request,"Coach/Chat.html")

def ajaxchatview(request):
    tid = request.GET.get("tid")
    user = tbl_coach.objects.get(id=request.session["cid"])
    chat_data = tbl_chat.objects.filter((Q(coach_from=user) | Q(coach_to=user)) & (Q(user_from=tid) | Q(user_to=tid))).order_by('chat_time')
    return render(request,"Coach/ChatView.html",{"data":chat_data,"tid":int(tid)})

def clearchat(request):
    tbl_chat.objects.filter(Q(coach_from=request.session["cid"]) & Q(user_to=request.GET.get("tid")) | (Q(user_from=request.GET.get("tid")) & Q(coach_to=request.session["cid"]))).delete()
    return render(request,"Coach/ClearChat.html",{"msg":"Chat Deleted Sucessfully...."})

Coach/templates/Coach/Changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password</title>
</head>
<body>
    <form  method="post" action="">
        {% csrf_token %}
        <table>
       
        <tr>
            <td>
        <label for="opassword">Old Password</label></td>
        <td><input type="password" id="txt_opassword" name="txt_opassword" required></td>
 </tr>
 <tr>
    <td>
<label for="npassword">New Password</label></td>
<td><input type="password" id="txt_npassword" name="txt_npassword" required></td>
</tr>
<tr>
    <tr>
        <td>
    <label for="cpassword">Confirm Password</label></td>
    <td><input type="password" id="txt_cpassword" name="txt_cpassword" required></td>
    </tr>
    <tr>
    <td colspan="2" align="center">
        <button type="submit">
            Change
        </button>
        <button type="reset">
            Cancel
        </button>
    </td>
</tr>
        </table>
        </form>
        {% if msg %}
        <script>
            alert("{{msg}}")
        </script>
        {% endif %}
        </body>
        </html>
        

Coach/templates/Coach/Chat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- <link rel="stylesheet" href="path/to/your/css/styles.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<style>
    .par-card{
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .head-sec {
        width: 840px;
        background-color: #6c8cfc;
        padding: 17px;
        border-radius: 10px;
        border-bottom: 1px solid white;
        margin-left: 8px;
        margin-top: 8px;
        display: flex;
        gap: 10px;
    }
    .content {
        display: flex;
        gap: 10px;
        width: 840px;
    }
    .option {
        color:white;
        font-size: 20px;
    }
    .option-content {
        width: 115px;
        padding: 10px;
        background-color: #90caf9;
        border-radius: 10px;
        position: absolute;
        left: 1036px;
        margin-top: 4px;
        display: none;
        transition: transform 3.9s ease-in-out;
    }
    .option-selection {
        display: flex;
        gap: 5px;
        flex-direction: column;
        align-items: center;
    }
    .con-card {
        width: 840px;
        padding: 24px;
        border-radius: 10px;
        background-color: transparent;
        min-height: 520px;
    }
    .message-card {
        padding: 24px;
        /* border-radius: 10px; */
        border-top: 1px solid white;
    }
    .message-box {
        padding: 10px;
        width: 750px;
        margin-left: 5px;
        border: none;
        background-color: #F5F5F5;
        border-radius: 10px;
    }
    .chat-card {
        /* background-color: #3f32f41c; */
        padding: 10px;
        box-shadow: 0 0 33px;
        border-radius: 10px;
    }
    .btn {
        background-color: transparent;
        border: none;
    }
    .ic-size {
        font-size: 20px;
        color: #6c8cfc;
    }
    .font {
        color: white;
        font-size: 20px;
        font-family: Poor Richard;
    }
    .r-mess {
        padding: 5px;
        background-color: #BBDEFB;
        border-radius: 10px;
        max-width: 555px;
        width: fit-content;
    }
    .s-mess {
        padding: 5px;
        background-color: #90caf9;
        border-radius: 10px;
        max-width: 555px;
        width: fit-content;
    }
    .par-r-mess {
        display: flex;
        flex-direction: column;
        justify-content: flex-start;
        padding-bottom: 5px;
    }
    .par-s-mess {
        display: flex;
        flex-direction: column;
        padding-bottom: 5px;
        align-items: flex-end;
    }
    .s-time {
        padding: 2px;
        font-size: 9px;
        display: flex;
        justify-content: flex-end;
    }
    .r-time {
        padding: 2px;
        font-size: 9px;
    }
    .con-width {
        min-width: 35px;
    }
    .scroll-con {
        overflow-y: scroll;
        height: 581px;
    }
    .scroll-con::-webkit-scrollbar {
      display: none;
    }


    .sk-folding-cube {
        margin: 20px auto;
        width: 40px;
        height: 40px;
        position: absolute;
        left: 50%;
        top: 50%;
        -webkit-transform: rotateZ(45deg);
                transform: rotateZ(45deg);
    }

    .sk-folding-cube .sk-cube {
        float: left;
        width: 50%;
        height: 50%;
        position: relative;
        -webkit-transform: scale(1.1);
            -ms-transform: scale(1.1);
                transform: scale(1.1); 
    }
    .sk-folding-cube .sk-cube:before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: #333;
        -webkit-animation: sk-foldCubeAngle 2.4s infinite linear both;
                animation: sk-foldCubeAngle 2.4s infinite linear both;
        -webkit-transform-origin: 100% 100%;
            -ms-transform-origin: 100% 100%;
                transform-origin: 100% 100%;
    }
    .sk-folding-cube .sk-cube2 {
        -webkit-transform: scale(1.1) rotateZ(90deg);
                transform: scale(1.1) rotateZ(90deg);
    }
    .sk-folding-cube .sk-cube3 {
        -webkit-transform: scale(1.1) rotateZ(180deg);
                transform: scale(1.1) rotateZ(180deg);
    }
    .sk-folding-cube .sk-cube4 {
        -webkit-transform: scale(1.1) rotateZ(270deg);
                transform: scale(1.1) rotateZ(270deg);
    }
    .sk-folding-cube .sk-cube2:before {
        -webkit-animation-delay: 0.3s;
                animation-delay: 0.3s;
    }
    .sk-folding-cube .sk-cube3:before {
        -webkit-animation-delay: 0.6s;
                animation-delay: 0.6s; 
    }
    .sk-folding-cube .sk-cube4:before {
        -webkit-animation-delay: 0.9s;
                animation-delay: 0.9s;
    }
    @-webkit-keyframes sk-foldCubeAngle {
        0%, 10% {
            -webkit-transform: perspective(140px) rotateX(-180deg);
                    transform: perspective(140px) rotateX(-180deg);
            opacity: 0; 
        } 25%, 75% {
            -webkit-transform: perspective(140px) rotateX(0deg);
                    transform: perspective(140px) rotateX(0deg);
            opacity: 1; 
        } 90%, 100% {
            -webkit-transform: perspective(140px) rotateY(180deg);
                    transform: perspective(140px) rotateY(180deg);
            opacity: 0; 
        } 
    }

    @keyframes sk-foldCubeAngle {
        0%, 10% {
            -webkit-transform: perspective(140px) rotateX(-180deg);
                    transform: perspective(140px) rotateX(-180deg);
            opacity: 0; 
        } 25%, 75% {
            -webkit-transform: perspective(140px) rotateX(0deg);
                    transform: perspective(140px) rotateX(0deg);
            opacity: 1; 
        } 90%, 100% {
            -webkit-transform: perspective(140px) rotateY(180deg);
                    transform: perspective(140px) rotateY(180deg);
            opacity: 0; 
        }
    }
    .blur-page {
        margin-top: -10px;
        height: 100%;
        width: 99%;
        background-color: rgba(255, 255, 255, 0.729);
        position: absolute;
    }
    .profile {
        display: none;
        width: 100%;
        background-color: #ffffffed;
        justify-content: center;
        align-items: center;
        height: 100vh;
        position: absolute;
        left: 0px;
        top: 0px;
    }
    .profile-close {
        display: flex;
        justify-content: flex-end;
        align-items: center;
    }
    .cl-ic {
        font-size: 27px;
        color: #d4d2d2;
    }
    .date-con {
        display: flex;
        justify-content: center;
        align-items: center;
        color: gray;
        font-size: 13px;
        margin-bottom: 10px;
    }
</style>
<body>
    <div class="blur-page" id="b-page">
        <div class="sk-folding-cube">
            <div class="sk-cube1 sk-cube"></div>
            <div class="sk-cube2 sk-cube"></div>
            <div class="sk-cube4 sk-cube"></div>
            <div class="sk-cube3 sk-cube"></div>
        </div>
    </div>
    <div class="profile" id="profile">
        <div>
            <div class="profile-close" onclick="close_profile()">
                <i class="fa-regular fa-circle-xmark cl-ic"></i>
            </div>
            <div>
                <img src="{{user.user_photo.url}}" width="300px" height="300px" alt="">
            </div>
        </div>
    </div>    
    <div class="par-card">
        <div class="chat-card">
            <div class="head-sec" id="changeable">
                <div class="content">
                    <div  onclick="open_profile()">
                        <img src="{{user.user_photo.url}}" width="40px" height="40px" style="border-radius: 50%;" alt="">
                    </div>
                    <div class="font">
                        {{user.user_name}}
                        <input type="hidden" name="txt_id" id="txt_id" value="{{user.id}}">
                    </div>
                </div>
                <div>
                    <button style="background-color: transparent;border: none;" onclick="handleOption()"><i class="fa-solid fa-ellipsis-vertical option"></i></button>
                </div>
            </div>
            <div class="option-content" id="option-div">
                <div class="option-selection">
                    <div><a  style="text-decoration: none;color: white;" onclick="clearchat()"><i class="fa-solid fa-broom"></i>&nbsp;Clear Chat</a></div>
                </div>
            </div>
           <div class="scroll-con" id="sc-down">
            <div class="con-card" id="conversation" onclick="date_see()">
                
            </div>
           </div>
            <div class="message-card">
                <label for="photo_data">
                    <i class="fas fa-paperclip ic-size"></i>
                </label>
                <input type="file" name="photo_data" id="photo_data" style="display: none;" onchange="sendChat('{{user.id}}')">
                <input type="text" name="txt_msg" class="message-box" id="txt_msg" placeholder="Type your message..." autocomplete="off">
                <button class="btn" type="submit" onclick="sendChat('{{user.id}}')"><i class="fas fa-paper-plane ic-size"></i></button>
            </div>
        </div>
    </div>
</body>
</html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
      document.getElementById("b-page").style.display = "none"
      document.getElementById("profile").style.display = "none"
      var dateval = false
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = cookies[i].trim();
                // Check if this cookie string begins with the name we want
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }


    function sendChat(tid) {
        var msg = document.getElementById("txt_msg").value;
        var fileInput = document.getElementById("photo_data");
        var file = fileInput.files[0];
        if (msg.trim() === "" && !file)
        {

        }
        else
        {
            var fd = new FormData()
            fd.append("file",file)
            fd.append("tid",tid)
            fd.append("msg",msg)
            var ur = "{% url 'webcoach:ajaxchat' %}"
            var csrftoken = getCookie('csrftoken');
            $.ajax({
                type:'POST',
                url: ur,
                data: fd,
                processData: false,
                contentType: false,
                headers: { "X-CSRFToken": csrftoken }, // Include CSRF token in headers
                success: function (data) {
                    // $("#selplace").html(data);
                    document.getElementById('txt_msg').value = "" 
                    document.getElementById("photo_data").value = ""
                    $('#sc-down').animate({scrollTop: $('#sc-down')[0].scrollHeight});
                    var element = document.getElementById("sc-down");
                    element.scrollTop = element.scrollHeight - element.clientHeight;
                },
            });
        }
    };

    function viewChat() {
        var id = document.getElementById("txt_id").value
        var ur = "{% url 'webcoach:ajaxchatview' %}"
        $.ajax({
            url: ur,
            data: { tid: id, },
            success: function (data) {
                $("#conversation").html(data);
            }
        });
    };

    viewChat()
    setInterval(viewChat,800)

    function handleOption() {
        let Check = document.getElementById('option-div')
        if(Check.style.display === "none" )
        document.getElementById("option-div").style.display = "block"
        else
        document.getElementById("option-div").style.display = "none"

    }

    function clearchat() {
        var id = document.getElementById("txt_id").value
        var ur = "{% url 'webcoach:clearchat' %}"
        document.getElementById("b-page").style.display = "block"
        $.ajax({
            url: ur,
            data: { tid: id, },
            success: function (data) {
                // console.log(data);
                document.getElementById("b-page").style.display = "none"
                alert(data)
                location.reload()
            }
        });
    };

    function close_profile() {
        document.getElementById("profile").style.display = "none"
    }

    function open_profile() {
        document.getElementById("profile").style.display = "flex"
    }

    // function date_see() {
    //     dateval = !dateval
    //     if (dateval == true)
    //     {
    //         var elements = document.getElementsByClassName("date-con");
    //         for (var i = 0; i < elements.length; i++) {
    //             elements[i].style.display = "flex";
    //         }
    //     }
    //     else
    //     {
    //         var elements = document.getElementsByClassName("date-con");
    //         for (var i = 0; i < elements.length; i++) {
    //             elements[i].style.display = "none";
    //         }
    //     }
    // }

</script>

Coach/templates/Coach/ClearChat.html
{{msg}}

Coach/templates/Coach/CoachHP.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
</head>
<body>
   

    {% csrf_token %}
        <h2>Welcome Coach</h2>
        {{data.coach_name}}
        <br>
<a href="{% url 'webcoach:ViewCoach'  %}">View Profile</a><br>
<a href="{% url 'webcoach:Trainingdetails'  %}">Add Training</a><br>

<a href="{% url 'webcoach:AddSubscription'  %}">Add Subscription</a><br>
<a href="{% url 'webcoach:Followers' %}">View Followers</a><br>
      
     </body></html>

Coach/templates/Coach/DailyPlan.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <table border="2" align="center">
            <tr>
                <th>
                    Day
                </th>
                <td>
                    <input type="text" name="txt_day" id="txt_day">
                </td>
            <tr>
                <th>
                    Workout
                </th>
                <td>
                    <input type="text" name="txt_workout" id="txt_workout">
                </td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <button type="submit" id="btn_submit" value="Submit">Submit</button>
                    <button type="reset">Reset</button>
                </td>
            </tr>
            </tr>
        </table>
    </form>
    <br>
    <table border="2" align="center">
        <tr>
            <th>
                Day
            </th>
            <th>
                Workouts
            </th>
            <th>
                Add workout
            </th>
        </tr>
        {% for i in data %}
        <tr>
            <td>
                {{i.dailyplan_day }}
            </td>
            <td>
                {{ i.dailyplan_wcount }}
            </td>
            <td><a href="{% url 'webcoach:Workout' i.id %}">Add Workout</a></td>
        </tr>
        {% endfor %}
    </table>
</body>

</html>

Coach/templates/Coach/Followers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <table border="2" align="center">
        <tr>
            <td align="center" colspan="2">
                <h2>MY FOLLOWERS</h2>
            </td>
        </tr>
        {% for i in data %}
       
        <tr>
            <td>
                Name:
            </td>
            <td>
                {{i.user.user_name}}
            </td>
            <td><a href="{% url 'webcoach:chatpage' i.id %}">Chat</a></td>
        </tr>
     {% endfor %}
</body>
</html>

Coach/templates/Coach/Viewprofile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Profile</title>
</head>
<body>
    <form  method="post" action="">
        {% csrf_token %}
        <table>
        <h2>PROFILE</h2>
        <tr>
           
            <td>
                <img src="{{data.coach_photo.url}}" alt="">
                
            </td>
        </tr>
        <tr>
            <td>
        <label for="name"> Name:</label></td>
        <td>{{data.coach_name}}</td>
 </tr>
 <tr>
    <td>
        <label for="email">Email:</label></td>
    <td>

        {{data.coach_email}}
        
    </td>
    </tr>
    <tr>
        <td>
            <label for="contact">Contact:</label>
        </td>
        <td>
            {{data.coach_contact}} 
        </td>
    </tr>
    <tr>
        <td>
            <label for="address">Adress:</label>
            <td>
                {{data.coach_address}}
            </td>
        </td>
    </tr>
        <tr>
            <td>
                <label for="gender">Gender:</label>
            </td>
            <td>
                {{data.coach_gender}}
            </td>
        </tr>
        <tr>
            <td>
                <label for="dob">Date of Birth:</label>
            </td>
            <td>
                {{data.coach_dob}}            
            </td>
        </tr>
       
       <tr>
        <td>District:</td>
        <td>
            {{data.place.district.district_name}}
        </td>
       </tr>
       <tr>
        <td>Place:</td>
        <td>
            {{data.place.place_name}}
        </td>
       </tr>
       

   
       <tr>
        <td colspan="2" align="center">
            <button><a href="{% url 'webcoach:EditCoach'  %}">Edit Profile</a></button>
            <button><a href="{% url 'webcoach:EPCoach' %}">Change  password</a></button>
        
        </td>
       </tr> 
    </table>
    </form>
</body>

</html>